spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro_jwt_demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: lengleng
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

authentication:
  jwt:
    secret: SDFLMO59U2MLASN192
    # Token is valid 24 hours
    token-validity-in-seconds: 86400
    token-validity-in-seconds-for-remember-me: 2592000
logging:
  level:
    root: info
server:
  error:
    include-stacktrace: on_trace_param
